name: Playwright Cucumber Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    # No manual inputs needed for auto-trigger on push/pull_request
      environment:
        description: 'Select environment'
        required: true
        default: 'test'
        type: choice
        options:
          - test
      test_type:
        description: 'Select test type'
        required: true
        default: 'test:crud'
        type: choice
        options:
          - test:ui:ci
          - test:crud
          - test:ui

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Set Environment Variables
      run: |
        echo "TRELLO_API_KEY=${{ secrets.TRELLO_API_KEY }}" >> $GITHUB_ENV
        echo "TRELLO_API_TOKEN=${{ secrets.TRELLO_API_TOKEN }}" >> $GITHUB_ENV
        echo "TRELLO_BOARD_ID=${{ secrets.TRELLO_BOARD_ID }}" >> $GITHUB_ENV
        echo "TRELLO_BOARD_LIST_ID=${{ secrets.TRELLO_BOARD_LIST_ID }}" >> $GITHUB_ENV
        echo "TRELLO_LOGIN_EMAIL=${{secrets.TRELLO_LOGIN_EMAIL}}" >> $GITHUB_ENV
        echo "TRELLO_LOGIN_PASSWORD=${{secrets.TRELLO_LOGIN_PASSWORD}}" >> $GITHUB_ENV
        echo "TRELLO_2FA_SETUP_KEY=${{secrets.TRELLO_2FA_SETUP_KEY}}" >> $GITHUB_ENV

    - name: Run Playwright Cucumber tests
      run: npm run test:ui:ci

    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/

    - name: Upload Cucumber test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report
        path: cucumber-json/

    - name: Upload Playwright traces
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: test-results/
